version: "3.5"

services:
  web:
    build: .
    restart: always
    ports:
      - target: 80
        published: 8080
    volumes:
      # Add your plugins here
      # Example: Plugin named my-plugin contained in parent directory
      - type: bind
        source: ../my-plugin
        target: /var/www/html/wp-content/plugins/my-plugin

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: classicpress
      MYSQL_USER: username
      MYSQL_PASSWORD: dev
